version: '3'

services:

  web:
    container_name: windsurf
    build:
      context: .
      secrets:
        - env
    command: bash -c "sleep infinity"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONDEVMODE=1
    env_file:
      - .env
    networks:
      - windsurf

networks:
  windsurf:
    name: windsurf

secrets:
  env:
    file: .env