version: '3.8'

name: windsurf

services:

  web:
    container_name: windsurf
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sleep infinity"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONDEVMODE=1
      - REDIS_URL=redis://cache:6379/0
    depends_on:
      - cache
    env_file:
      - .env
    networks:
      - windsurf

  cache:
    container_name: windsurf-cache
    image: redis:8.0.3-alpine3.21
    restart: always
    volumes:
      - windsurf-cache:/data
    networks:
      - windsurf

networks:
  windsurf:
    name: windsurf

volumes:
  windsurf-cache:
    name: windsurf-cache