version: '3'

services:

  database:
    container_name: windsurf-database
    image: pgvector/pgvector:pg16
    restart: always
    environment:
      - POSTGRES_USER=langchain
      - POSTGRES_PASSWORD=langchain
      - POSTGRES_DB=langchain
    volumes:
      - windsurf-database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - windsurf

  web:
    container_name: windsurf
    build:
      context: .
      secrets:
        - env
    command: bash -c "sleep infinity"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONDEVMODE=1
      - DATABASE_URL=postgresql+psycopg://langchain:langchain@database:5432/langchain
    env_file:
      - .env
    networks:
      - windsurf

networks:
  windsurf:
    name: windsurf

volumes:
  windsurf-database:
    name: windsurf-database

secrets:
  env:
    file: .env